import { Octokit } from "octokit";
import { z } from "zod";

import type { CreatedGithubIssue, IssueDraft } from "@/lib/types";

const GITHUB_OWNER = "ashish921998";
const GITHUB_REPO = "product-team";

const issueDraftSchema = z.object({
  title: z.string().min(1),
  why: z.string().min(1),
  acceptance_criteria: z.array(z.string().min(1)).min(1),
  priority: z.enum(["P1", "P2", "P3"]),
  ice_score: z.number().min(1).max(10),
  success_metric: z.string().min(1),
  event_to_instrument: z.object({
    name: z.string().min(1),
    properties: z.array(z.string().min(1)).min(2).max(3)
  }),
  drop_off_point: z.string().min(1),
  guardrail_metric: z.string().min(1).optional()
});

const createIssuesInputSchema = z.tuple([issueDraftSchema, issueDraftSchema, issueDraftSchema]);

type RepoContext = {
  owner: string;
  repo: string;
  readme: string | null;
  recent_issue_titles: string[];
};

function getOctokit() {
  const auth = process.env.GITHUB_TOKEN;

  if (!auth) {
    throw new Error("GITHUB_TOKEN is missing");
  }

  return new Octokit({ auth });
}

function getRequestHeaders() {
  return {
    "X-GitHub-Api-Version": "2022-11-28"
  };
}

function decodeBase64Utf8(content: string) {
  return Buffer.from(content, "base64").toString("utf8");
}

function summarizeReadme(readme: string) {
  return readme
    .replace(/```[\s\S]*?```/g, "")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/^#{1,6}\s+/gm, "")
    .replace(/\[(.*?)\]\((.*?)\)/g, "$1")
    .replace(/\r/g, "")
    .trim()
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean)
    .slice(0, 12)
    .join("\n")
    .slice(0, 1800);
}

export async function getGithubRepoContext(): Promise<RepoContext> {
  const octokit = getOctokit();

  const [readmeResponse, issuesResponse] = await Promise.all([
    octokit.rest.repos
      .getReadme({
        owner: GITHUB_OWNER,
        repo: GITHUB_REPO,
        headers: getRequestHeaders()
      })
      .catch(() => null),
    octokit.rest.issues.listForRepo({
      owner: GITHUB_OWNER,
      repo: GITHUB_REPO,
      state: "open",
      sort: "updated",
      per_page: 10,
      headers: getRequestHeaders()
    })
  ]);

  const readme =
    readmeResponse?.data.content && readmeResponse.data.encoding === "base64"
      ? summarizeReadme(decodeBase64Utf8(readmeResponse.data.content))
      : null;

  const recentIssueTitles = issuesResponse.data
    .filter((issue) => !issue.pull_request)
    .map((issue) => issue.title)
    .slice(0, 8);

  return {
    owner: GITHUB_OWNER,
    repo: GITHUB_REPO,
    readme,
    recent_issue_titles: recentIssueTitles
  };
}

function buildIssueBody(issue: IssueDraft) {
  return [
    "## Why",
    issue.why,
    "",
    "## Acceptance Criteria",
    ...issue.acceptance_criteria.map((criterion) => `- ${criterion}`),
    "",
    "## Product Packet",
    `- Priority: ${issue.priority}`,
    `- ICE score: ${issue.ice_score}`,
    `- Success metric: ${issue.success_metric}`,
    issue.guardrail_metric ? `- Guardrail metric: ${issue.guardrail_metric}` : null,
    `- Drop-off point: ${issue.drop_off_point}`,
    `- Event to instrument: ${issue.event_to_instrument.name}`,
    `- Event properties: ${issue.event_to_instrument.properties.join(", ")}`,
    "",
    "## Priority",
    issue.priority,
    "",
    "Generated by ProductTeam.ai"
  ]
    .filter(Boolean)
    .join("\n");
}

export async function createGithubIssues(drafts: IssueDraft[]): Promise<CreatedGithubIssue[]> {
  const validDrafts = createIssuesInputSchema.parse(drafts);
  const octokit = getOctokit();
  const createdIssues: CreatedGithubIssue[] = [];

  for (const draft of validDrafts) {
    const response = await octokit.rest.issues.create({
      owner: GITHUB_OWNER,
      repo: GITHUB_REPO,
      title: draft.title,
      body: buildIssueBody(draft),
      headers: getRequestHeaders()
    });

    createdIssues.push({
      title: draft.title,
      url: response.data.html_url,
      number: response.data.number,
      priority: draft.priority
    });
  }

  return createdIssues;
}
