import { Octokit } from "octokit";
import { z } from "zod";

import type { CreatedGithubIssue, IssueDraft } from "@/lib/types";

const GITHUB_OWNER = "ashish921998";
const GITHUB_REPO = "product-team";

const issueDraftSchema = z.object({
  title: z.string().min(1),
  why: z.string().min(1),
  acceptance_criteria: z.array(z.string().min(1)).min(1),
  priority: z.enum(["P1", "P2", "P3"])
});

const createIssuesInputSchema = z.tuple([issueDraftSchema, issueDraftSchema, issueDraftSchema]);

function getOctokit() {
  const auth = process.env.GITHUB_TOKEN;

  if (!auth) {
    throw new Error("GITHUB_TOKEN is missing");
  }

  return new Octokit({ auth });
}

function getRequestHeaders() {
  return {
    "X-GitHub-Api-Version": "2022-11-28"
  };
}

function buildIssueBody(issue: IssueDraft) {
  return [
    "## Why",
    issue.why,
    "",
    "## Acceptance Criteria",
    ...issue.acceptance_criteria.map((criterion) => `- ${criterion}`),
    "",
    `## Priority`,
    issue.priority,
    "",
    "Generated by ProductTeam.ai"
  ].join("\n");
}

export async function createGithubIssues(drafts: IssueDraft[]): Promise<CreatedGithubIssue[]> {
  const validDrafts = createIssuesInputSchema.parse(drafts);
  const octokit = getOctokit();

  const createdIssues = await Promise.all(
    validDrafts.map(async (draft) => {
      const response = await octokit.rest.issues.create({
        owner: GITHUB_OWNER,
        repo: GITHUB_REPO,
        title: draft.title,
        body: buildIssueBody(draft),
        headers: getRequestHeaders()
      });

      return {
        title: draft.title,
        url: response.data.html_url,
        number: response.data.number,
        priority: draft.priority
      } satisfies CreatedGithubIssue;
    })
  );

  return createdIssues;
}
